### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by huangxun201314** [wuranxu/pedis#7]
项目启动白屏，yarn start报错：
(node:17760) electron: Failed to load URL: http://localhost:5173/ with error: ERR_CONNECTION_REFUSED

**Comment by wuranxu** [comment]
由于vite不支持使用redis包，所以需要用electron启动。具体步骤如下:
```
# 启动react应用
yarn dev
# 启动electron
yarn start
```

**Comment by huangxun201314** [comment]
> 由于vite不支持使用redis包，所以需要用electron启动。具体步骤如下:
> 
> ```
> # 启动react应用
> yarn dev
> # 启动electron
> yarn start
> ```

多谢，顺便问下怎么打包？

**Comment by wuranxu** [comment]
package.json里面有一些名流，vite build打包成html，接着electron-builder打包成exe/dmg
